Figaro.require_keys(
                    "SECRET_KEY_BASE",
                    "VK_APP_ID",
                    "VK_APP_SECRET",
                    "VK_REDIRECT_PATH",
                    "FB_APP_ID",
                    "FB_APP_SECRET",
                    "TWITTER_API_KEY",
                    "TWITTER_API_SECRET",
                    "INSTAGRAM_APP_ID",
                    "INSTAGRAM_SECRET",
                    "APP_URL",
                    "AWS_ACCESS_KEY_ID",
                    "AWS_SECRET_ACCESS_KEY",
                    "AWS_REGION",
                    # "AWS_BUCKET",
                    "SENDGRID_USERNAME",
                    "SENDGRID_PASSWORD",
                    # "SLACK_WEB_HOOK"
                   )
